### ISSUE TITLE
Analytics Tracking Issue

### ISSUE THREAD

**Issue by bethannenc** [cfpb/regulations-site#665]
Hi - 

We realized today that the tracking code that is being sent to the CFPB wide analytics account is not working from the /eregulations pages. The reason for this is that the tracking code is sending a universal tag to our account, however, our account has not been migrated to universal. All tags sending data to the CFPB wide account should be using the classic code. 

**Our basic pageview tracking:** 

script type="text/javascript"

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-20466645-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

/script

**Please insert classic tracking code into all pages of eregulations. Thank you!**

**Comment by ascott1** [comment]
This isn't an issue any longer.
