### ISSUE TITLE
Update README to include front-end building instructions

### ISSUE THREAD

**Issue by cmc333333** [cfpb/regulations-site#698]
Right now, the readme implies that the app works after `./bin/django runserver`, but that's not accurate since the JS files need to be built. Notably:

```[25/Mar/2015 19:30:46] "GET /static/regulations/js/built/regulations.min.js HTTP/1.1" 404 1721```

As building the JS is required now, can "quick start" build instructions be added?

**Comment by grapesmoker** [comment]
I will do that tomorrow.

**Comment by KimberlyMunoz** [comment]
Fixed in #701
