### ISSUE TITLE
Run JS unit tests in Travis

### ISSUE THREAD

**Issue by contolini** [cfpb/regulations-site#718]
I noticed the mocha unit tests @KimberlyMunoz wrote aren't being run by Travis. Can `grunt mocha_istanbul` safely be added to the end of .travis.yml? Or is it more complicated than that?

**Comment by KimberlyMunoz** [comment]
I think that should be safe to do.

**Comment by ascott1** [comment]
https://github.com/cfpb/regulations-site/pull/731 closes this
