### ISSUE TITLE
Possible problem with loading indicator on defined terms?

### ISSUE THREAD

**Issue by willbarton** [cfpb/regulations-site#736]
![](http://i.imgur.com/LCCy0Xg.gif)

This happens for me running a fresh copy of regulations-site locally but the loading indicator appears to work as expected on [consumerfinance.gov/eregulations](http://www.consumerfinance.gov/eregulations/).

Worth investigating?

**Comment by ascott1** [comment]
> Worth investigating?

Ha! Definitely.

**Comment by ascott1** [comment]
I think this was caused by some changes when implementing the SxS loading indicator.
