### ISSUE TITLE
Back navigation from footnotes is off by a few lines

### ISSUE THREAD

**Issue by vrajmohan** [cfpb/regulations-site#777]
For example, see http://www.consumerfinance.gov/eregulations/sxs/1026-1-c/2013-28210?from_version=2015-18239. Click on footnote "160" to navigate to the footnote text. Clicking now on the "return" link does not take you back to where you came from. It's off by 2-3 lines.

**Comment by ascott1** [comment]
This is unique to direct links to the Section by Section analysis, which container the sticky orange header. When a user navigates to the SxS from the reg text the header is not sticky. To fix this bug, this should first be standardized.
